@startuml package-by-feature

title Package By Feature

!include https://raw.githubusercontent.com/bionic-hillbilly/plantuml-themes/master/themes/light-theme.puml

package Betclic.Payment.Deposits {
    rectangle DepositsController
    rectangle IDepositsService <<interface>>
    rectangle DepositsService
    rectangle IDepositsRepository <<interface>>
    rectangle DepositsRepository

    DepositsController --> IDepositsService : uses
    IDepositsService <|-- DepositsService : implements
    DepositsService --> IDepositsRepository : uses
    IDepositsRepository <|-- DepositsRepository : impelements
}

package Betclic.Payment.DepositEligibility {
    rectangle DepositEligibilityController
    rectangle IDepositEligibilityService <<interface>>
    rectangle DepositEligibilityService
    rectangle IDepositEligibilityRepository <<interface>>
    rectangle DepositEligibilityRepository

    DepositEligibilityController --> IDepositEligibilityService : uses
    IDepositEligibilityService <|-- DepositEligibilityService : implements
    DepositEligibilityService --> IDepositEligibilityRepository : uses
    IDepositEligibilityRepository <|-- DepositEligibilityRepository : impelements
}

@enduml
